




/*
     FILE ARCHIVED ON 19:20:14 May 26, 2015 AND RETRIEVED FROM THE
     INTERNET ARCHIVE ON 2:42:18 Nov 10, 2015.
     JAVASCRIPT APPENDED BY WAYBACK MACHINE, COPYRIGHT INTERNET ARCHIVE.

     ALL OTHER CONTENT MAY ALSO BE PROTECTED BY COPYRIGHT (17 U.S.C.
     SECTION 108(a)(3)).
*/
window.tplogs = true;